### ISSUE TITLE
Error while accessing graph  from browser

### ISSUE THREAD

**Issue by ParvinderParashar** [hasura/graphql-bench#10]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1151, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1037, in add_context
    output_value = func(*args, **kwargs)
  File "/graphql-bench/plot.py", line 93, in updateGraph
    benchMarkIndex=int(benchMarkIndex)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by ParvinderParashar** [comment]
<img width="1280" alt="Screenshot 2019-04-23 at 2 31 06 PM" src="https://user-images.githubusercontent.com/18110496/56568404-8a57e900-65d4-11e9-920c-c701a651410f.png">
[logs1.txt](https://github.com/hasura/graphql-bench/files/3106751/logs1.txt)

**Comment by ParvinderParashar** [comment]
[logs1.txt](https://github.com/hasura/graphql-bench/files/3106751/logs1.txt)
